{
  testAsyncWriteThrows(new Error("explicitly_thrown_by_test"));
}
