{
  try {
    handler.completed(context);
  }
 catch (  Exception x) {
    logger.info("Exception while notifying handler " + handler,x);
  }
catch (  Error x) {
    logger.info("Exception while notifying handler " + handler,x);
    throw x;
  }
}
