{
  Throwable failure=this.failure;
  if (failure != null)   throw new ExecutionException(failure);
  return promise;
}
