{
  try {
    callback.failed(t);
  }
 catch (  Throwable e) {
    LOG.warn("Uncaught exception",e);
  }
}
