{
  try {
    if (callback != null)     callback.failed(failure);
  }
 catch (  Throwable x) {
    LOG.info("Exception while notifying callback " + callback,x);
  }
}
