{
  try {
    listener.onFailure(response,failure);
  }
 catch (  Throwable x) {
    LOG.info("Exception while notifying listener " + listener,x);
  }
}
