{
  Exception ex=new Exception("failed");
  IOFuture future=new DoneIOFuture(ex);
  assertTrue(future.isDone());
  try {
    future.isComplete();
    Assert.fail();
  }
 catch (  ExecutionException e) {
    Assert.assertEquals(ex,e.getCause());
  }
  long start=System.currentTimeMillis();
  try {
    future.block();
    Assert.fail();
  }
 catch (  ExecutionException e) {
    Assert.assertEquals(ex,e.getCause());
  }
  Assert.assertThat(System.currentTimeMillis() - start,lessThan(10L));
  start=System.currentTimeMillis();
  try {
    future.block(1000,TimeUnit.MILLISECONDS);
    Assert.fail();
  }
 catch (  ExecutionException e) {
    Assert.assertEquals(ex,e.getCause());
  }
  Assert.assertThat(System.currentTimeMillis() - start,lessThan(10L));
  final AtomicBoolean ready=new AtomicBoolean(false);
  final AtomicReference<Throwable> fail=new AtomicReference<>();
  future.setCallback(new Callback<Object>(){
    @Override public void completed(    Object context){
      ready.set(true);
    }
    @Override public void failed(    Object context,    Throwable cause){
      fail.set(cause);
    }
  }
,null);
  assertFalse(ready.get());
  assertEquals(ex,fail.get());
}
