{
  try {
    _task.run();
  }
 catch (  Throwable x) {
    LOG.debug("Exception while executing task " + _task,x);
  }
}
